### PR TITLE
add port instance method to set/get the port number to use

### PR DESCRIPTION
**Pull request by a6502**
I needed a way to ask question to a (test) resolver on another port, so i added a port method to do that.

### CODE REVIEW

**Comment by cdybedahl** [comment]
Awesome. Could you add documentation for the method? If not, I'll do so later, bit it'd be nice to have it in the same commit.

**Comment by a6502** [comment]
Yes I can, but not today. I'll try to add it tomorrow.

**Comment by a6502** [comment]
Ok, added a couple of lines of documentation.
Also added the qr method to the documentation of LDNS::Packet, I had to look in the xs source to see that it was already there.

**Comment by cdybedahl** [comment]
I think that method got added in a hurry when we needed it for the DNSSEC tests in Zonemaster. Thanks for noticing!

**Comment by cdybedahl** [comment]
By the way, is this something you want in a release version on CPAN as soon as possible, or can it wait a  week or five in case something else shows up?

**Comment by a6502** [comment]
Oh, it can wait, for now i'm using my local forked version anyways.

**Pull request merged**
